A lot of new changes

diff --git a/lock b/lock
--- a/lock
+++ b/lock
@@ -1,8 +1,8 @@
 #!/usr/bin/sh
-#scrot /tmp/screen_locked.png
-#convert /tmp/screen_locked.png -scale 10% -scale 1000% /tmp/screen_locked.png
-#i3lock -i /tmp/screen_locked.png
-#i3lock -c 002b36
-#i3lock -c 000000
-exec i3lock -c 002B36
-#i3lock -i /home/atmoz/background-locked.png
+
+# This check prevents lock-screen-before-suspend.service to fail
+if ! pidof i3lock > /dev/null; then
+    exec i3lock -c 002B36
+else
+    exit 0
+fi
